# Generated by Django 5.1.6 on 2025-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0002_alter_item_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Both", "Both")],
                default="Both",
                max_length=10,
            ),
        ),
    ]
