# Generated by Django 5.1.6 on 2025-03-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("my_app", "0003_item_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCarehub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_id", models.PositiveIntegerField()),
                ("comment", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
