# Generated by Django 5.1.6 on 2025-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingslot",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
