# Generated by Django 5.1.6 on 2025-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_bookingslot_shop_end_bookingslot_user_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingslot",
            name="rated",
            field=models.BooleanField(default=False),
        ),
    ]
