# Generated by Django 4.2.20 on 2025-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_bookingslot_rated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingslot",
            name="user_end",
            field=models.BooleanField(default=True),
        ),
    ]
