# Generated by Django 5.1.6 on 2025-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0002_area_district_division_popularlandmark_upazilla_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="PopularLandmark",
            new_name="Landmark",
        ),
    ]
