# Generated by Django 5.1.6 on 2025-02-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0004_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
