# Generated by Django 5.1.6 on 2025-02-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0005_alter_services_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "item_description",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="myApp.service",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Items",
        ),
    ]
