# Generated by Django 5.1.6 on 2025-02-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("myApp", "0006_rename_services_service_item_delete_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="shop_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=255)),
                ("shop_title", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_info", models.TextField(blank=True, null=True)),
                (
                    "shop_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("shop_owner", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_customer_count", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "shop_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("shop_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_area", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "shop_landmark_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("member_since", models.DateField(auto_now_add=True)),
                (
                    "shop_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shop_services", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="shop_gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="shop_gallery/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="shop_profile.shop_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shop_service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("availability", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="myApp.service",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="shop_profile.shop_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shop_worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="worker_profiles/"
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(help_text="Experience in years"),
                ),
                (
                    "expertise",
                    models.ManyToManyField(related_name="experts", to="myApp.item"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shop_review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=1)),
                ("review", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop_profile.shop_profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("shop", "user")},
            },
        ),
    ]
