# Generated by Django 5.1.6 on 2025-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=255)),
                ("shop_title", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_info", models.TextField(blank=True, null=True)),
                (
                    "shop_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("shop_owner", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_customer_count", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "shop_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("shop_website", models.URLField(blank=True, null=True)),
                ("shop_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shop_area", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "shop_landmark_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop_landmark_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("member_since", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
