# Generated by Django 5.1.6 on 2025-02-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="shopprofile",
            name="shop_email",
        ),
        migrations.AddField(
            model_name="myuser",
            name="user_type",
            field=models.CharField(
                choices=[("user", "User"), ("shop", "Shop Owner"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shopprofile",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_profile",
                to="shop_profile.myuser",
            ),
            preserve_default=False,
        ),
    ]
