# Generated by Django 5.1.6 on 2025-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopgallery',
            name='description',
            field=models.CharField(blank=True, default='No description available', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_info',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_landmark_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_landmark_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_landmark_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_landmark_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_landmark_5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shopworker',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profile.jpg', upload_to='ShopWorker/'),
        ),
        migrations.AlterField(
            model_name='shopworker',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
