# Generated by Django 5.1.6 on 2025-02-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0001_initial"),
        # ("user_profile", "0002_alter_user_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop_review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_reviews",
                to="user_profile.user_profile",
            ),
        ),
    ]
