# Generated by Django 5.1.6 on 2025-02-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0002_alter_shop_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop_profile",
            name="shop_address",
        ),
        migrations.RemoveField(
            model_name="shop_profile",
            name="shop_category",
        ),
        migrations.RemoveField(
            model_name="shop_profile",
            name="shop_services",
        ),
        migrations.CreateModel(
            name="shop_schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="shop_profile.shop_profile",
                    ),
                ),
            ],
        ),
    ]
