# Generated by Django 5.1.6 on 2025-03-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0002_alter_shopgallery_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="shop_picture",
            field=models.ImageField(blank=True, null=True, upload_to="ShopGallery/"),
        ),
    ]
