# Generated by Django 5.1.6 on 2025-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shop_profile",
            "0003_shopgallery_shopreview_shopschedule_shopservice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shopworker",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
