# Generated by Django 5.1.6 on 2025-02-25 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0003_remove_shop_profile_shop_address_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="shop_profile",
            new_name="ShopProfile",
        ),
    ]
