# Generated by Django 5.1.6 on 2025-02-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_rename_services_service_item_delete_items"),
        ("shop_profile", "0004_rename_shop_profile_shopprofile"),
        ("user_profile", "0003_rename_user_profile_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shop_review",
            new_name="ShopReview",
        ),
        migrations.RenameModel(
            old_name="shop_schedule",
            new_name="ShopSchedule",
        ),
        migrations.RenameModel(
            old_name="shop_service",
            new_name="ShopService",
        ),
        migrations.RenameModel(
            old_name="Shop_worker",
            new_name="ShopWorker",
        ),
        migrations.CreateModel(
            name="ShopGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="ShopGallery/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="shop_profile.shopprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="shop_gallery",
        ),
    ]
