# Generated by Django 5.1.6 on 2025-02-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0005_rename_shop_review_shopreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="shop_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopworker",
            name="shop",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopworker",
                to="shop_profile.shopprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shopgallery",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopgallery",
                to="shop_profile.shopprofile",
            ),
        ),
        migrations.AlterField(
            model_name="shopreview",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopreview",
                to="shop_profile.shopprofile",
            ),
        ),
        migrations.AlterField(
            model_name="shopschedule",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopschedule",
                to="shop_profile.shopprofile",
            ),
        ),
        migrations.AlterField(
            model_name="shopservice",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopservice",
                to="shop_profile.shopprofile",
            ),
        ),
    ]
