# Generated by Django 5.1.6 on 2025-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_profile", "0005_alter_shopworker_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopworker",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shopworker",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
