# Generated by Django 5.1.6 on 2025-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_rename_services_service_item_delete_items"),
        ("shop_profile", "0006_shopprofile_shop_website_shopworker_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopworker",
            name="expertise",
            field=models.ManyToManyField(
                blank=True, related_name="experts", to="myApp.item"
            ),
        ),
    ]
