# Generated by Django 5.1.6 on 2025-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_profile", "0006_shopworker_total_reviews_alter_shopworker_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopreview",
            name="reviewer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
