# Generated by Django 5.1.6 on 2025-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0007_alter_shopworker_expertise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopworker",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="ShopWorker/"),
        ),
    ]
