# Generated by Django 5.1.6 on 2025-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_profile", "0007_shopreview_reviewer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("payment", "Payment"),
                    ("message", "Message"),
                    ("general", "General"),
                    ("cancel", "cancel"),
                ],
                default="general",
                max_length=10,
            ),
        ),
    ]
