# Generated by Django 5.1.6 on 2025-02-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_rename_services_service_item_delete_items"),
        ("shop_profile", "0008_alter_shopworker_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopservice",
            name="availability",
        ),
        migrations.AlterField(
            model_name="shopservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopservices",
                to="myApp.item",
            ),
        ),
    ]
