# Generated by Django 5.1.6 on 2025-02-25 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0009_remove_shopservice_availability_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopservice",
            old_name="service",
            new_name="item",
        ),
    ]
