# Generated by Django 5.1.6 on 2025-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_profile", "0010_rename_service_shopservice_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="password",
            field=models.CharField(default=123456, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shopworker",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="shopworker",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
